### ISSUE TITLE
Improve dependency management

### ISSUE THREAD

**Issue by jvmancuso** [jvmancuso/safe-grid-agents#31]
Right now, the repos we rely on are a bit of a mess.  In particular, gym-ai-safety-gridworlds has a broken setup.py and ai-safety-gridworlds doesn't have one at all.  We've also been relying on a submodule for using ai-safety-gridworlds, which I'd prefer to avoid long-term.  Here's a plan for fixing this situation.

- [x] Maintain a fork of `ai-safety-gridworlds` with a proper setup.py (can ideally PR this back to the main repo)
- [x] Create the `safe-grid-gym` repo
  - [x] Hard fork of `gym_ai_safety_gridworlds` using David's fork
  - [x] Hard fork of [`ai-safety-gridworlds-viewer`](https://github.com/n0p2/ai-safety-gridworlds-viewer)
  - [x] Simplify setup.py, pointing to our fork of the ai-safety-gridworlds repo
  - [x] Make sure to give proper attribution in the license
- [x] Simplify our own setup.py to match all of this

**Comment by david-lindner** [comment]
Do we want to keep using the fork we are currently using which also contains the modified tomato watering environment (https://github.com/jvmancuso/ai-safety-gridworlds)? Could be a problem, if we want to submit a PR for the setup.py

**Comment by jvmancuso** [comment]
We can submit the PR from a different branch but have our fork maintain our own environments as needed

**Comment by jvmancuso** [comment]
Decided to include `[ai-safety-gridworlds-viewer`](https://github.com/n0p2/ai-safety-gridworlds-viewer) in this, edited top-level comment to reflect changes

**Comment by jvmancuso** [comment]
Fixed on master as of #32
