### ISSUE TITLE
Reproducibility

### ISSUE THREAD

**Issue by jvmancuso** [jvmancuso/safe-grid-agents#50]
#### Needed for reproducibilty
- [x] Log each run's hyperparameter config
- [x] When args.seed isn't provided, we want to sample one randomly and save it for reproducibility
- [x] Write a script that logs the current repo commit with each training run
- [ ] Dockerize the repo for environment installation
- Stretch: use nvidia docker image for use with GPUs

**Comment by alok** [comment]
See the tune branch for an implementation of the above. I added the commit ID to config though it may be better off on its own. Seeds are randomly sampled and set for each experiment if not provided. Hyperparam config is logged to Tensorboard too.
