### ISSUE TITLE
Sanity check SpikyCRMDP PPO

### ISSUE THREAD

**Issue by jvmancuso** [jvmancuso/safe-grid-agents#51]
Get SpikyCRMDP working with one of the Toy Gridworlds, debug if needed

**Comment by david-lindner** [comment]
So I spend some time today testing (and as expected debugging) the crmdp agent. The general logic was correct, but a couple of things were not working, see #52 

Now, I get reasonable results on both toy gridworlds. It seems like this agent can solve both of them after just a few iterations.

## Corruption in the corners
```
python main.py -dc -E 1000 -EE 10 -V 10 -S 1 -L log/corners/solver_E_100_EE_10_V_10_S_1_ppo_cnn_l_0.001_r_10_e_5 corners ppo-crmdp -l 0.001 -r 10 -e 5
```

![image](https://user-images.githubusercontent.com/16326959/51566763-c1afe000-1e95-11e9-8cba-3aa712e52ac9.png)


## Corruption in the way
```
python main.py -dc -E 1000 -EE 10 -V 10 -S 1 -L log/way/solver_E_100_EE_10_V_10_S_1_ppo_cnn_l_0.001_r_10_e_5 way ppo-crmdp -l 0.001 -r 10 -e 5
```
![image](https://user-images.githubusercontent.com/16326959/51566640-6251d000-1e95-11e9-995f-a077a5099af3.png)
